-- Migration 0005: Add population_affected column to infrastructure
-- This column stores the WorldPop-derived population count: sum of all 100m
-- WorldPop cell populations whose centres fall within the asset's impact radius.
--
-- After this migration runs, backfill with:
--   psql $DATABASE_URL -f supabase/update-population.sql
--
-- Generated by scripts/precompute-worldpop-population.py

ALTER TABLE infrastructure ADD COLUMN population_affected integer;

-- Index for population-based queries (e.g. sorting assets by population at risk)
CREATE INDEX IF NOT EXISTS infra_population_affected_idx ON infrastructure (population_affected);
